fhoeben/hsac-fitnesse-fixtures

src/main/java/nl/hsac/fitnesse/fixture/Environment.java
src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java

Support setting HTTP headers on GET verb

---

src/main/java/nl/hsac/fitnesse/fixture/slim/web/SeleniumDriverSetup.java

With JSON I can type each capability (not just everything is a string)

public boolean connectToDriverAtWithCapabilities(String url, String capabilitiesInJson)

---

src/main/java/nl/hsac/fitnesse/fixture/Environment.java
src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java
src/main/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java
src/main/java/nl/hsac/fitnesse/fixture/util/HttpServer.java
wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/JsonHttpTest/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/content.txt

Add support for HTTP verb PUT

---

pom.xml
src/main/java/nl/hsac/fitnesse/fixture/slim/mobile/AndroidAppTest.java
src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java
src/main/java/nl/hsac/fitnesse/fixture/slim/web/SeleniumDriverSetup.java
src/main/java/nl/hsac/fitnesse/fixture/util/selenium/SeleniumHelper.java
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/DemoTestCase001/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/DemoTestCase001/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/SetUp/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/SetUp/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/TearDown/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/TearDown/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/TestData/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/TestData/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/NegenTweeAppDemo/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/DominosPerfectPepperoni/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/DominosPerfectPepperoni/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/GherkinPepperoni/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/GherkinPepperoni/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/ScenarioLibrary/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/ScenarioLibrary/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/SetUp/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/SetUp/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/TearDown/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/TearDown/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/ThuisBezorgdDemo/properties.xml
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/content.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/AndroidAppTests/properties.xml

Added androidAppFixture
Extended SeleniumDriverSetup with possibility to ask for an Appium AndroidDriver 
Some extensions to SeleniumHelper (quick and -sometimes very- dirty)
Some documentation and examples in FitNesse wiki
#47

Extended fixture set with appium android native app fixture

---

pom.xml
src/main/java/nl/hsac/fitnesse/fixture/util/JsonHelper.java
src/main/java/nl/hsac/fitnesse/junit/HsacFitNesseRunner.java
src/main/java/nl/hsac/fitnesse/junit/selenium/SeleniumDriverFactoryFactoryBase.java
src/main/java/nl/hsac/fitnesse/junit/selenium/SeleniumJsonGridDriverFactoryFactory.java
src/test/java/nl/hsac/fitnesse/fixture/util/JsonHelperTest.java

#63 
Tried the included jsonhelper first, but that has issues with maps within maps
Not sure if you willing to use/include Gson, otherwise I have to write a parser.
Unfortunately you will have to escape all ", or add a replace ' by " inside the new Factory
Examples that I tested (launch the chrome correct)
```
mvn clean test-compile failsafe:integration-test -DseleniumGridUrl=http://localhost:4444/wd/hub -DseleniumJsonCapabilities="{\"browserName\":\"chrome\",\"chromeOptions\":{\"mobileEmulation\":{\"deviceName\":\"Google Nexus 5\"}}}" -DfitnesseSuiteToRun=HsacExamples.SlimTests.BrowserTests.ScriptTest
or
mvn clean test-compile failsafe:integration-test -DseleniumGridUrl=http://localhost:4444/wd/hub -DseleniumJsonCapabilities="{\"browserName\":\"chrome\",\"chromeOptions\":{\"mobileEmulatio …
```

seleniumJsonCapabilities 

---

src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/selenium/SeleniumHelper.java
src/test/java/nl/hsac/fitnesse/fixture/util/SeleniumHelperTest.java
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/AriaLabelledTest/content.txt
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/ClickByLabelOrButton/content.txt
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/ClickOnLinkTest/content.txt
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/GridTest/content.txt
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/ListTests/content.txt

@teunisnl can you verify whether this fix addresses the problem you encountered?

Find text containing &nbsp;

---

wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests.wiki
wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/Angular2CalculatorTest.wiki

Here's an example test for a Angular 2 port of the calculator app
As it's in plunker I had to load open the page using BrowserTest first and wait for the app to load

Example test for Ng2BrowserTest

---

wiki/FitNesseRoot/HsacExamples/SymbolSamples.wiki

(cherry picked from commit a2234fc)
To be honest, I only changed three lines, the compare tool is giving me fake credits.

Included additions to randomstring ranges in wikipage SymbolSamples

---

wiki/FitNesseRoot/HsacExamples/SymbolSamples.wiki

Now that the random Email and randomIban are in the plugin, I figured I might as well set this one for you for when you create a new release.

Added randomEmail and randomIban to the SymbolSamples

---

src/main/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/JsonPathHelper.java
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/HttpTest/JsonHttpTest.wiki
wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests.wiki

New version of https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/136

Added a method to json http test to check if json path exists in a json file

---

src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/selenium/SeleniumHelper.java

also moved double click to selenium helper

waitAfterScroll to protected

---

src/main/java/nl/hsac/fitnesse/fixture/slim/FileFixture.java
src/main/java/nl/hsac/fitnesse/fixture/util/FileUtil.java
src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java
src/test/resources/testFileFixture.txt
wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/FileFixture.wiki

Basically this pull request is about just one small utility function; "append a line to an existing file".
This exists in the slim filefixture class and the fileutil class.
I have also added a FileFixture junit test, for some functions, and one text file in resources which is being used in that test.

Added function to FileFixture to append a line to a file.

---

src/test/java/nl/hsac/fitnesse/fixture/util/BsnUtilTest.java

made an extra unittest for the bsn functionality

extra test for the checkbsn functionality

---

wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/RichFacesTest.wiki

The form that was used is no longer on the triodos website

Fixed RichFaces test

---

src/main/java/nl/hsac/fitnesse/fixture/Environment.java
src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java
src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java
wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests.wiki
wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpsWithoutCertificateVerification.wiki

This PR is meant to fix #123. It has been tested by hand, and I also performed the manual test mentioned in https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/202#issue-181219021 to verify that this PR does not break enabling/disabling compression.
Automated testing is possible, but would require setting up an entire HttpsServer with a variety of certificates specifically for testing this one command. The test would probably add more code and complexity than the feature itself. Alternatively, badssl.com could be used for automated testing, but [their readme](https://github.com/chromium/badssl.com#disclaimer) specifically says it's meant for manual testing only.
Manual testing can be done using the following test page (requires multiple runs and commenting lines because throwing an …

Allow enabling and disabling SSL certificate verification

---

src/main/java/nl/hsac/fitnesse/fixture/slim/DateTimeCalculatorFixture.java
src/test/java/nl/hsac/fitnesse/fixture/slim/DateTimeCalculatorFixtureTest.java
wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/DateTimeCalculatorFixture.wiki

A simple (library) fixture to add/subtract years, months, days, hours, minutes, seconds to/from a given date.
Use case: we test some applications that set dates or times we'd like to validate in the system, relative to user input/events (f.e. end date automatically set x weeks from now, or interval timing based on event times)

Date time calculator fixture

---

src/main/java/nl/hsac/fitnesse/fixture/util/JsonPathHelper.java
src/test/java/nl/hsac/fitnesse/fixture/util/JsonPathHelperTest.java

As mentioned in https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/254. A correction on the error message.

getting a list instead of one error

---

pom.xml

Updated to chromedriver 74.0.3729.6. Driver 73.x does not play nice with chrome 74.

Chromedriver 74

---

pom.xml
wiki/FitNesseRoot/HsacExamples/SymbolSamples.wiki

contains https://github.com/fhoeben/hsac-fitnesse-plugin/pull/36 and documentation

Include plugin version 1.28.0 

---

pom.xml

Add support for new (chromium based) edgedriver

Chromium based edgedriver

---

pom.xml

Add latest chromedriver 84.0.4147.30

update to latest chromedriver 84.0.4147.30

---

pom.xml

See https://github.com/webdriverextensions/webdriverextensions-maven-plugin/issues/49

Revert webdriverextension

---

pom.xml

Small update: https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.13

Update toolchain-plugin to 2.0.13

---

changelog.md
pom.xml

Webdriver updates

---

changelog.md
pom.xml

EdgeDriver 108.0.1462.42
ChromeDriver 108.0.5359.71
FitNesse 20221102

update chromium based webdrivers to v108 and update FitNesse to 20221102

---

.gitlab-ci.yml
changelog.md
docker/chrome/Dockerfile
pom.xml
src/main/java/nl/hsac/fitnesse/fixture/slim/web/SeleniumDriverSetup.java
src/main/java/nl/hsac/fitnesse/fixture/util/JsonFormatter.java

Fitnesse 20221219

---

changelog.md
pom.xml

- ChromeDriver 110.0.5481.77
- Edgedriver 110.0.1587.41

Update chromium based webdrivers to v110

---

.github/workflows/other.yml
.gitlab-ci.yml
changelog.md
docker/chrome/Dockerfile
pom.xml
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/SuiteSetUp.wiki

See https://stackoverflow.com/questions/75680149/unable-to-establish-websocket-connection for changes in starting browser (with UI) in SuiteSetUp

Update chromium based webdrivers to 111

---

changelog.md
pom.xml

ChromeDriver 112.0.5615.49
Edgedriver 112.0.1722.34

Update chromium based webdrivers 112

---

.github/workflows/other.yml
.gitlab-ci.yml
changelog.md
docker/chrome/Dockerfile
pom.xml
wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/SuiteSetUp.wiki

- Remove workaround remote-allow-origins #481
- Update Edgedriver 113.0.1774.9
- Update Chromedriver 113.0.5672.24

Update chromium based webdrivers 113 and remove workaround
