src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java, src/main/java/nl/hsac/fitnesse/fixture/slim/TimerFixture.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpResponse.java, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/HttpTest/XmlHttpTest/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/TimerFixture/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/TimerFixture/properties.xml
Adds request handling time to Http Test. And new utility fixture to measure elapsed time (and output current time) during test: `TimerFixture`
=> Response time measurement in HttpTest

src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/AlertHandlingTest/content.txt
=> Ensure 'take screenshot' when alert is active does not stop test execution

src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpResponse.java, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpCookieHandling/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpCookieHandling/properties.xml, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpGetFollowRedirectTest/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpPost3UsingFreemarkerTemplateTest/content.txt, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/content.txt
Add ability to check the cookies sent by a server as part of an http response.
Allow a sequence of requests where the cookies received are sent on the next request.
=> HttpTest can work with cookies

src/main/java/nl/hsac/fitnesse/fixture/Environment.java, src/main/java/nl/hsac/fitnesse/fixture/slim/SlimFixture.java, src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java, src/main/java/nl/hsac/fitnesse/fixture/util/selenium/PageSourceSaver.java, src/main/java/nl/hsac/fitnesse/fixture/util/selenium/SeleniumHelper.java, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/FrameHandlingTests/FrameHandling/content.txt, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/FrameHandlingTests/IframeHandling/content.txt
Previously the file created by 'save page source' (and the page content captured on exception) in BrowserTest only captured the content of the top-level page (e.g. the 'default content').
With this pull requests we also capture the content of any (i)frames the page may contain.
=> Also save frame's content with 'save page source'

pom.xml, src/main/java/nl/hsac/fitnesse/fixture/Environment.java, src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java, src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java, src/main/java/nl/hsac/fitnesse/fixture/util/selenium/CookieConverter.java, wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/UseCookiesForHttpTest/content.txt
- Use latest apache http client
- By default use 'standard' cookie handling
- No longer allow cookie 'version' to be set when copying browser cookies (it shouldn't be needed)
- Make http client configuration easier to change from Java code
- Allow http client usage to be modified more easily by creating subclass
=> Latest apache http client version

README.md, src/main/java/nl/hsac/fitnesse/junit/HsacFitNesseRunner.java, src/test/java/nl/hsac/fitnesse/fixture/FixtureDebugTest.java, wiki/FitNesseRoot/HsacExamples/TaggedTestcases.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/SuiteSetUp.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T001.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T002.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T003.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T004.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T005.wiki, wiki/FitNesseRoot/HsacExamples/TaggedTestcases/T006NoTags.wiki
Added possibility to in- and exclude tags from a command-line run.
This can be done by specifying the SuiteFilter and ExcludeSuiteFilter annotations on FixtureDebugTest, or by specifying system properties 'suiteFilter' and/or 'excludeSuiteFilter'.
The ExcludeSuiteFilter interface and getExcludeSuiteFilter method for excluding tags could also be implemented fitnesse-side IMO. They are in HsacFitnesseRunner now, so that we can use a system property.
I have kept the syntax exactly as it is in FitNesseRunner for the SuiteFilter (that one does accept a sysprop value as it is in FitNesse)
An example suite with tagged tests is provided in HsacExamples.TaggedTestcases
=> Added support for filtering suites by in- and excluding tags

pom.xml, src/main/java/nl/hsac/fitnesse/fixture/util/JsonHelper.java, src/main/java/nl/hsac/fitnesse/junit/selenium/SeleniumJsonGridDriverFactoryFactory.java, src/test/java/nl/hsac/fitnesse/fixture/util/JsonHelperTest.java
We would like to start chrome with args/extenions; both expect a list of strings
This works:
```
|script|list fixture   |
|add   |start-maximized|
|$args=|copy list      |
|script         |map fixture   |
|set value      |$args|for|args|
|$chromeoptions=|copy map      |
|script          |selenium driver setup             |
|start driver for|chrome|with profile|$chromeoptions|
|show            |driver description                |
```
but it does not work using json ```
-DseleniumJsonCapabilities="{\"browserName\":\"chrome\", \"chromeOptions\":{\"args\":[\"start-maximized\"]}}"```
Tried it with the use of Gson then it works fine; (included in this pull request)
Maby you can fix your parser for the new test so gson isn't needed
```
=> A new test to test JSON and arrays

.travis.yml, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/FileUploadTest.wiki
Using phantom 2.1.1 on travis (instead of 1.x.x) should make build more stable, and allows file upload
=> Use phantomjs 2.1.1 on Travis-CI

src/main/java/nl/hsac/fitnesse/fixture/slim/DateFormatFixture.java, wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/DateFormatFixture.wiki
Extra constructor option for DateFormatFixture so that we can also translate to and from date strings that are formatted using local acronyms or day/month names.
See the example page for a usage example.
=> Updated date format fixture to be able to work with localized date strings

pom.xml
Latest versions of freemarker allow for (among other things) auto-escaping of non-valid xml characters (such as ampersand) to reduce the risk of generating invalid requests.
See: https://freemarker.apache.org/docs/dgui_misc_autoescaping.html
We can now start a freemarker xml template with `<#ftl output_format="XML">` to enable automatic escaping.
=> Updated Freemarker to latest version

src/main/java/nl/hsac/fitnesse/fixture/slim/web/SeleniumDriverSetup.java, src/main/java/nl/hsac/fitnesse/fixture/util/selenium/driverfactory/LocalDriverFactory.java, wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/SuiteSetUp.wiki
We wanted to use the "ie.ensureCleanSession" capability with internet explorer but couldn't, so I added the possibility to hsac. Had a bit of spare time today to turn it into a pull request so that others may benefit from it, too
=> Allow starting IE with capabilities and give an example

src/main/java/nl/hsac/fitnesse/fixture/Environment.java, src/main/java/nl/hsac/fitnesse/fixture/slim/HttpTest.java, src/main/java/nl/hsac/fitnesse/fixture/util/HttpClient.java, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests.wiki, wiki/FitNesseRoot/HsacExamples/SlimTests/HttpTests/HttpCompressionTest.wiki
This PR is meant to fix #56. I tried to write tests for it, but the mockXmlServer does not seem suited to feed binary data to apache's HttpClient. I tested it by hand using the following test page:
```
|script  |http test                                            |
|note    |Test normal request without compression support      |
|get from|http://fakerestapi.azurewebsites.net/api/activities/1|
|show    |response                                             |
|script                                                         |
|note     |Force gzip compression (this should give gibberish)  |
|set value|gzip        |for header       |Accept-Encoding       |
|get from |http://fakerestapi.azurewebsites.net/api/activities/1|
|show     |response                                             |
|script …
```
=> Allow enabling and disabling content compression support

wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/RichFacesTest.wiki, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/HttpTest/HttpGetFileTest.wiki, wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/FileFixture.wiki
Some Slim acceptance tests were failing. Fixed the following:
- RichFaces test was failing because triodos.nl was changed -> Changed url and button to click.
- FileTest failed on Windows because of a line endings issue -> Explicitly set line endings to Unix style before check. 
- HttpGetFileTest could only be run once, subsequent runs failed, because old mock response file was never deleted and newly created mock response files got an unexpected name. -> Added deletion of mock response file to the test.
=> Fixed some acceptance tests

src/main/java/nl/hsac/fitnesse/junit/selenium/LocalSeleniumDriverClassFactoryFactory.java
When using -DseleniumBrowser=... it's also possible to supply a profile through -DseleniumJsonProfile=...
When using -DseleniumDriverClass=... the same was not possible
=> Be able to use a browser profile when using a local seleniumDriverClass

src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java
Currently, testDelete fails when run on its own, because the file to delete initially does not exist. This pull request copies the file into position first before deleting.
Please let me know if you want to discuss the changes more.
=> Ensuring testDelete can run on its own

src/main/java/nl/hsac/fitnesse/fixture/slim/JsonFixture.java, src/main/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTest.java, src/test/java/nl/hsac/fitnesse/fixture/slim/JsonFixtureTest.java, src/test/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTestTest.java, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/HttpTest/JsonHttpTest.wiki
return null with empty elementOfJsonPath
=> empty elementOfJsonPath

src/main/java/nl/hsac/fitnesse/fixture/util/selenium/driverfactory/LocalDriverFactory.java
Since edge is now chromium based, we can also pass it a profile map to better parameterize it. (i.e. run headless, start-maximized set screen resolution, etc)
This PR ensures that when a a map is passed to startDriverForWithProfile and msedge is requested, that the profile map is applied as capabilities. (ms:edgeOptions capability)
=> Support map of capabilities for (chromium) edge, like chrome

pom.xml
* Contains [Bootstrap-plus 2.0.12](https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.12)
* Adds homepage URL from dependency pom.xml to !VersionChecker table
* Enables Filtering of (Suite)SetUp and -TearDown pages from recent test history responder
=> Update Praegus Toolchain Plugin to 2.0.10

src/main/java/nl/hsac/fitnesse/fixture/Environment.java, src/main/java/nl/hsac/fitnesse/fixture/slim/FileFixture.java, src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java, wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/FileFixture.wiki
Previously, http://files url's referencing the wiki's file section were not translated to an actual file path when they were not translated to a html link first when used with i.e. FileFixture.
This PR allows to use http://files references from a literal table (`!|table|`)
=> Allow using plaintext http://files urls

pom.xml, src/main/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTest.java, src/main/java/nl/hsac/fitnesse/fixture/util/JsonHelper.java, src/main/java/nl/hsac/fitnesse/fixture/util/NamespaceContextImpl.java, src/test/java/nl/hsac/fitnesse/fixture/slim/JsonHttpTestTest.java, src/test/java/nl/hsac/fitnesse/fixture/util/JsonHelperTest.java, src/test/java/nl/hsac/fitnesse/fixture/util/XmlHttpResponseTest.java
The following 10 tests:
`nl.hsac.fitnesse.fixture.slim.JsonHttpTestTest#testPutValuesAsJson`
`nl.hsac.fitnesse.fixture.slim.JsonHttpTestTest#testPostValuesAsJson`
`nl.hsac.fitnesse.fixture.slim.JsonHttpTestTest#testDeleteValuesAsJson`
`nl.hsac.fitnesse.fixture.slim.JsonHttpTestTest#testFormatJson`
`nl.hsac.fitnesse.fixture.slim.JsonHttpTestTest#testFormatJsonArray`
`nl.hsac.fitnesse.fixture.util.JsonHelperTest#testFormatSimple`
`nl.hsac.fitnesse.fixture.util.JsonHelperTest#testSortingOnNumber` 
`nl.hsac.fitnesse.fixture.util.JsonHelperTest#testSortingOnString`
`nl.hsac.fitnesse.fixture.util.XmlHttpResponseTest#testCheckXPathsIncorrect`
`nl.hsac.fitnesse.fixture.util.NamespaceContextImplTest#testAddMultipleGet`
are flaky tests. The first 3 tests depend on a function called …
=> Fix Nondeterministic Ordering in Tests

pom.xml
The currently included version 2.0.10 is *not compatible* with the parser changes in FitNesse 20201213. 
Version 2.0.11 is.
=> Update to latest toolchain-plugin

pom.xml
[Plugin v2.0.12](https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.12)
Contains Bootstrap-plus 2.0.14:
- Autocomplete now suggests all symbols from toolchain-plugin and hsac-plugin with their parameters
- Add option to sidepbar to pin a certain page as sidebar's root for testsuites with larger depth
- Add keyboard navigation to sidebar. Use arrow keys to navigate and expand/collapse. Open page with enter
- Allow NoLinksTables from FitNesse 20201213 in validator/context lookup
- Small styling improvements to scenario's in Context helper
=> Update praegus plugin to 2.0.12

pom.xml
4.30.0 is now failing with chrome 97, as it bundles chromedriver 95
=> update chrome and edgedriver to latest stable versions

src/main/java/nl/hsac/fitnesse/fixture/util/selenium/driverfactory/LocalDriverFactory.java
Missing break causes fall-through to default, which causes an error starting the browser when specifying a proxy server.
=> Add missing break to switch branch

.gitlab-ci.yml, changelog.md, docker/Dockerfile, docker/chrome/Dockerfile, docker/test/Dockerfile, docker/test/Dockerfile-local
By using docker base images also available on arm64 it becomes possible to build for AWS graviton or Mac M1 processors without changing the docker files
=> Use docker base images also available on arm64

pom.xml
Extract only executable to prevent subdirectory to be created inside webdrivers folder (breaking chrome tests in windows)
=> Chromedriver for windows zip now has >1 file

src/main/java/nl/hsac/fitnesse/sample/DevToolsBrowserTest.java
While running tests via docker `getSeleniumHelper().driver()` return RemoteWebDriver which not instance of `HasDevTools`.
We need to wrap driver to Augmenter for RemoteWebDriver capability.
=> Wrap devtools driver to Augmenter for RemoteWebDriver capability

src/main/java/nl/hsac/fitnesse/fixture/slim/FileFixture.java, src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java
Fix bug in FileFixture.setDirectory(String)  for argument "http://files/test" .
Bug can be observed throught script:
<pre>
|Import                       |
|nl.hsac.fitnesse.fixture.slim|
|script       |file fixture     |
|set directory|http://files/test|
|show         |get directory    |
^|script|
|set  directory|http://files/test|
|show          |get directory    |
</pre>
For my project, the first set directory/get directory will show
`     C:\git\toolchain\wiki\FitNesseRoot\files\test\`
and the second one shows
`     C:\git\toolchain\wiki\FitNesseRoot\files\\files\test\`
The first one is right.
The difference comes from the fact that the first call to setDirectory() gets argument `<a href="files/test">http://files/test</a>` .
In the code, for the second call to setDirectory() :
<pre> …
=> Fix bug for FileFixture.setDirectory("http://files/test")

src/main/java/nl/hsac/fitnesse/fixture/slim/web/SeleniumDriverSetup.java, src/main/java/nl/hsac/fitnesse/fixture/util/selenium/driverfactory/DriverClassNames.java, wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/SuiteSetUp.wiki
Since selenium 4.6.0, Selenium contains its own [driver manager](https://www.selenium.dev/blog/2022/introducing-selenium-manager/) that can automatically download the right webdriver version for a given browser. This manager can currently be used with selenium driver setup using the `|start driver|<driver class FQN>|` methods (or override from maven using the driverclass.
This, however, is not immediately clear to all users and using the right driver classname is apparently not easy for everyone..
This PR introduces new methods (startManagedDriverFor & startManagedDriverForWithProfile) that derive the driver class name from the readable driver name (chrome, edge, firefox, safari, internet_explorer) and make it explicit that a **selenium managed** driver is desired.
Now, when users would …
=> Shorthand method to start a selenium-managed driver

.github/workflows/main-java11.yml, .github/workflows/other-java11.yml, changelog.md, pom.xml, src/assembly/standalone-with-webdrivers.xml, src/assembly/standalone.xml, wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/SuiteSetUp.wiki
No longer bundle webdrivers in -standalone.zip, default to using the Selenium managed download that will download the proper webdriver on demand the first time it is used and will download one matching the installed browser version.
Add a separate -standalone-with-webdrivers.zip, which does include downloaded webdrivers as before. This package also contains drivers for Edge on MacOS (both Apple silicon and Intel)
=> Default to using managed webdriver

wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/ClickEmptySelectOption.wiki, wiki/FitNesseRoot/HsacAcceptanceTests/SlimTests/BrowserTest/SelectHandlingTest.wiki
Apparently finding nested `span` elements inside a `select`'s `option` tags no longer works on Linux Chrome, versions 129 and higher.
This failed the acceptance tests on GitHub, #691.
[According to the HTML spec such elements are actually not allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#technical_summary). So I removed those tests.
The functionality does still work on Mac M1, with chrome 131. For this reason I did not actually remove the functionality to attempt to find such elements from the code.
=> Remove acceptance tests failing on GitHub 
